# Generated by Django 3.1.7 on 2021-02-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.IntegerField(default=2000),
        ),
    ]
