# Generated by Django 3.1.7 on 2021-02-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.IntegerField(default=500),
        ),
    ]
